stages:
  
  get_data: 
    cmd: python get_data.py 
    outs:
    - data 
  
  mystage:
    cmd: python train.py
    deps:
    - data
    - train.py
    metrics:
    - metrics.json:
        cache: false
    plots:
    - loss.csv:
        cache: false
